/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseAutoHeightTextarea: typeof import('./src/components/base/BaseAutoHeightTextarea.vue')['default']
    BaseButton: typeof import('./src/components/base/BaseButton.vue')['default']
    BaseCheckout: typeof import('./src/components/base/BaseCheckout.vue')['default']
    BaseField: typeof import('./src/components/base/BaseField.vue')['default']
    BaseInput: typeof import('./src/components/base/BaseInput.vue')['default']
    BaseRadio: typeof import('./src/components/base/BaseRadio.vue')['default']
    BaseSelect: typeof import('./src/components/base/BaseSelect.vue')['default']
    BaseSelectMultiple: typeof import('./src/components/base/BaseSelectMultiple.vue')['default']
    BaseTextarea: typeof import('./src/components/base/BaseTextarea.vue')['default']
    BaseTooltip: typeof import('./src/components/atom/BaseTooltip.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    ImageBox: typeof import('./src/components/ImageBox.vue')['default']
    ImageList: typeof import('./src/components/ImageList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
