/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseCheckout: typeof import('./src/components/form/BaseCheckout.vue')['default']
    BaseField: typeof import('./src/components/form/BaseField.vue')['default']
    BaseInput: typeof import('./src/components/form/BaseInput.vue')['default']
    BaseRadio: typeof import('./src/components/form/BaseRadio.vue')['default']
    BaseSelect: typeof import('./src/components/form/BaseSelect.vue')['default']
    copy: typeof import('./src/components/form/BaseInput copy.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
