/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/base/BaseButton.vue')['default']
    BaseCheckout: typeof import('./src/components/base/BaseCheckout.vue')['default']
    BaseField: typeof import('./src/components/base/BaseField.vue')['default']
    BaseInput: typeof import('./src/components/base/BaseInput.vue')['default']
    BaseRadio: typeof import('./src/components/base/BaseRadio.vue')['default']
    BaseSelect: typeof import('./src/components/base/BaseSelect.vue')['default']
    BaseSelectTooltip: typeof import('./src/components/base/BaseSelectTooltip.vue')['default']
    BaseTooltip: typeof import('./src/components/atom/BaseTooltip.vue')['default']
    copy: typeof import('./src/components/ImageList copy.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Image: typeof import('./src/components/Image.vue')['default']
    ImageBox: typeof import('./src/components/ImageBox.vue')['default']
    ImageList: typeof import('./src/components/ImageList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
